"""add memory_type source importance updated_at

Revision ID: 6267d06bbf7d
Revises: 8f1846843ba7
Create Date: 2026-07-26 16:43:38.363703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6267d06bbf7d'
down_revision: Union[str, Sequence[str], None] = '8f1846843ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('memory_type', sa.String(length=32), nullable=False))
    op.add_column('memories', sa.Column('importance', sa.Float(), nullable=False))
    op.add_column('memories', sa.Column('source', sa.String(length=64), nullable=False))
    op.add_column('memories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'updated_at')
    op.drop_column('memories', 'source')
    op.drop_column('memories', 'importance')
    op.drop_column('memories', 'memory_type')
    # ### end Alembic commands ###
