"""add knowledge_type updated_at to knowledge

Revision ID: 6ddf797f1ac2
Revises: 6267d06bbf7d
Create Date: 2026-07-26 17:01:27.599499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddf797f1ac2'
down_revision: Union[str, Sequence[str], None] = '6267d06bbf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('knowledge_type', sa.String(length=32), nullable=False))
    op.add_column('knowledge', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge', 'updated_at')
    op.drop_column('knowledge', 'knowledge_type')
    # ### end Alembic commands ###
