"""add structured experience fields

Revision ID: 9e17fd366f0a
Revises: 07da808da589
Create Date: 2026-07-26 20:59:25.503203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e17fd366f0a'
down_revision: Union[str, Sequence[str], None] = '07da808da589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('context_json', sa.Text(), nullable=False))
    op.add_column('experiences', sa.Column('actions_json', sa.Text(), nullable=False))
    op.add_column('experiences', sa.Column('failures_json', sa.Text(), nullable=False))
    op.add_column('experiences', sa.Column('solution', sa.Text(), nullable=False))
    op.add_column('experiences', sa.Column('confidence', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'confidence')
    op.drop_column('experiences', 'solution')
    op.drop_column('experiences', 'failures_json')
    op.drop_column('experiences', 'actions_json')
    op.drop_column('experiences', 'context_json')
    # ### end Alembic commands ###
