"""add experience_type updated_at to experiences

Revision ID: c8a5dc9f37c7
Revises: 6ddf797f1ac2
Create Date: 2026-07-26 19:26:48.467404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a5dc9f37c7'
down_revision: Union[str, Sequence[str], None] = '6ddf797f1ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('experience_type', sa.String(length=32), nullable=False, server_default='interaction'))
    op.add_column('experiences', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'updated_at')
    op.drop_column('experiences', 'experience_type')
    # ### end Alembic commands ###
